---
- name: Stop Services
  hosts: all  #DB
  become: true
  become_method: sudo
  user: centos
  ignore_errors: true   #Don't stop if there are errors
  tasks: 
  - name: Stop r1soft on CentOS 7
    when: (ansible_distribution =="CentOS" and ansible_distribution_major_version == "7")
    systemd:
      name: sbm-agent
      state: stopped
    ignore_errors: true

     name: Stop r1soft on Centos 6
    when: (ansible_distribution =="CentOS" and ansible_distribution_major_version == "6")
    systemd:
      name: cdp-agent
      state: stopped
    ignore_errors: true

  - name: Stop Filebeat
      when: (ansible_distribution =="CentOS" and ansible_distribution_major_version == "7")
      systemd:
      name: filebeat
      state: stopped
    ignore_errors: true

  - name: Stop NRPE
      when: (ansible_distribution =="CentOS" and ansible_distribution_major_version == "7")
      systemd:
      name: nrpe
      state: stopped
    ignore_errors: true

  - name: Stop Mariadb
      when: (ansible_distribution =="CentOS" and ansible_distribution_major_version == "7")
      systemd:
      name: mariabd
      state: stopped
    ignore_errors: true

